### ISSUE TITLE
v2 API and Spec

### ISSUE THREAD

**Issue by ShaneKilkelly** [ExHammer/hammer#12]
As we've discussed in #9, the current API (`use Hammer, backend: Whatever`) is not ideal. Frankly, I lashed it together quickly for the sake of getting V1 out the door.

In this issue I will document my thoughts on an API for v2, and we can discuss pros/cons/etc.

**Comment by ShaneKilkelly** [comment]
# Requirements

- Needs to be easy to get started with.
- Needs to be easy to switch backends.
  - Change as little code/config as possible
  - Changable per running environment


# Current problems

The current implementation is awkward because it forces some
complexity and code onto the user. It also requires changing at least
two pieces of code in order to change backends.

This means that the backend can't be changed according to the environment.


# New Spec

- Backends are implemented as applications
- Configured via usual app config methods
- Backend must implement the `Hammer.Backend` behaviour,
  in a module `Hammer.Backend.Foo`
- Backends depend explicitely on the `hammer` package
- The `hammer` package will provide an application which starts the
  `Hammer.Backend.ETS` backend by default

**Comment by ShaneKilkelly** [comment]
Pull Request for `hammer`: https://github.com/ExHammer/hammer/pull/14

**Comment by ShaneKilkelly** [comment]
After playing around with this, it doesn't quite work. So I've come up with (what I think is) a better API:

- Backends implement two modules:
  - A `Hammer.Backend.Foo` implementation of `Hammer.Backend` behaviour
  - A `Hammer.Backend.Foo.Supervisor`, with a standard `start_link(config_kw_list)` interface
- One app, `hammer`
- Config via the `Mix.Config` interface
- When the `hammer` app starts, it looks at its config to determine the backend to use,
  and adds `Hammer.Backend.Foo.Supervisor` to it's supervision tree.

**Comment by sobolevn** [comment]
Yes, it should perfectly reasonable.

**Comment by ShaneKilkelly** [comment]
This is now ready for review, and I've released a `2.0.0-rc1` version of both `hammer` and `hammer_backend_redis`.

The [testbed](https://github.com/ExHammer/hammer-testbed/tree/test-new-api) also has a test branch (`test-new-api`), which is set up to use the new release-candidate versions of the libraries.

Here are the relevant pull-requests:

- https://github.com/ExHammer/hammer/pull/14
- https://github.com/ExHammer/hammer-backend-redis/pull/9
- https://github.com/ExHammer/hammer-testbed/pull/1

@sobolevn, would you mind giving these a look over when you have time?

**Comment by ShaneKilkelly** [comment]
Oh, and @sobolevn, thanks for the impetus to makes these changes, I think the result is much better than the v1 api :)

**Comment by ShaneKilkelly** [comment]
It looks like these pulls are ready to go, I'll try to get a release out in the next few days

**Comment by ShaneKilkelly** [comment]
Done in v2.0.0
