### ISSUE TITLE
A Plug helper, to make rate-limiting in Phoenix apps easy

### ISSUE THREAD

**Issue by ShaneKilkelly** [ExHammer/hammer#13]

**Comment by ShaneKilkelly** [comment]
Probably after the API re-design

**Comment by churchie317** [comment]
Hey! If you're looking for some help on this, I'd happily contribute.

**Comment by ShaneKilkelly** [comment]
Hi @churchie317, thanks for the offer. Sorry it's taken a while to look at this issue again.

I need to look over my notes again, and propose an appropriate API and such. Will post in this issue when I've got some traction on that.

**Comment by churchie317** [comment]
Sure thing, man. Happy to help!

**Comment by ShaneKilkelly** [comment]
I got bored this evening, so, work in progress: https://github.com/ExHammer/hammer-plug

**Comment by ShaneKilkelly** [comment]
Done, published `hammer_plug v1.0.0` https://github.com/ExHammer/hammer-plug
