### ISSUE TITLE
Allow multiple backends?

### ISSUE THREAD

**Issue by raarts** [ExHammer/hammer#15]
I am writing an API server (built on phoenix) which proxies API requests to multiple backends. I need to rate-limit globally, per-client, and per-backend. 
For the global, and per-client case I can use the ETS backend, but for the per-backend rate-limiting I would like to keep the info in Redis, to be usable across multiple instances of my app.

Is that possible?

BTW, using Redis would incur an extra round-trip to Redis on every request right?

**Comment by ShaneKilkelly** [comment]
Having thought about this a bit, I could imagine a solution where the hammer config takes a list/map of backend configs, with associated name atoms, then dispatched to each backend based on that name. We’d then need to add an extra func-head for each api function, with an extra parameter for the backend name.

**Comment by ShaneKilkelly** [comment]
On the latter question, yes, using redis means talking to the network. In practice this isn’t a big problem for large production apps which do lots of network stuff anyway. But it’s certainly a factor to consider before rolling out a redis solution.

**Comment by ShaneKilkelly** [comment]
Hammer `2.1.0` is out, with support for multiple backends
