### ISSUE TITLE
Support for Redis Sentinel

### ISSUE THREAD

**Issue by raarts** [ExHammer/hammer#16]
Who would run Redis without it? See [here](https://github.com/ananthakumaran/redix_sentinel)

**Comment by ShaneKilkelly** [comment]
This looks reasonably straight-forward. I may get around to this some time in the next few weeks. Pull-requests welcome otherwise.

**Comment by ShaneKilkelly** [comment]
Hoping to look at this over the holidays

**Comment by epinault** [comment]
@raarts unless you have time to support Redis Sentinel, I am not sure what s needed. The library you are pointing seems way out of date and that might cause more burden to use it. doesn t Redix deals with it? or even Nebulex?

**Comment by raarts** [comment]
Let's just close this.
