### ISSUE TITLE
Investigate Bottlenecks

### ISSUE THREAD

**Issue by ShaneKilkelly** [ExHammer/hammer#19]
I've got this weird feeling that we may be introducing a bottleneck by passing all rate-checks through one backend process. Performance seems pretty good in my tests, but I'd rather not be dragging down the throughput of applications unnecessarily. 

Actions:

- [ ] investigate worker-pool options
- [ ] experiment with making the backends a worker pool
- [ ] decide what to do

**Comment by ShaneKilkelly** [comment]
@sobolevn  any thoughts on this?

**Comment by sobolevn** [comment]
Maybe we should start with the benchmark tests and profiling?
So we will know what and how needs to be optimized.

**Comment by ShaneKilkelly** [comment]
This is addressed in version 4.0.0, just released.

**Comment by sobolevn** [comment]
@ShaneKilkelly awesome! 🎉
