### ISSUE TITLE
ArgumentError from Hammer.check_rate/3

### ISSUE THREAD

**Issue by nallwhy** [ExHammer/hammer#23]
I met ArgumentError frequently.

`** (CaseClauseError) no case clause matching: {:error, %ArgumentError{message: "argument error"}}`

When `call_backend/3` returns {:error, _}, `check_rate/4` returns {:error, _}.

I guess it's because of lack of pool.

**Comment by ShaneKilkelly** [comment]
Cool, glad that works.

Out of interest, what size are you setting the pool to? Curious to know at what scale the default stops being sufficient.
