### ISSUE TITLE
New logo for Hammer

### ISSUE THREAD

**Issue by reallinfo** [ExHammer/hammer#25]
Hello, i am a graphic designer. I wanted to contribute to Hammer and i designed a logo for Hammer. If you like it, i can send a pr. We can also organize a logo together.

![hammer](https://user-images.githubusercontent.com/36298335/40252534-50723e48-5ae5-11e8-9d27-1f94f646f112.jpg)

e.g. readmefile view

![view](https://user-images.githubusercontent.com/36298335/40252749-f790fd4a-5ae5-11e8-8fbb-794c7ef8e21f.png)

If you like it, which one do you prefer?

**Comment by ShaneKilkelly** [comment]
Looks good!

Could we see a variation in purple?

**Comment by reallinfo** [comment]
Of course, here you are;

![hammer](https://user-images.githubusercontent.com/36298335/40259784-4dd0f63c-5b00-11e8-86cd-2e8551767f0c.jpg)

**Comment by ShaneKilkelly** [comment]
Nice, I think the lower-right is the best. Really great work!

**Comment by reallinfo** [comment]
Okay, I think you are choose  option 2.   ? :)

![hammer](https://user-images.githubusercontent.com/36298335/40259976-1e1624a2-5b01-11e8-97e6-9ec1df3c0f35.jpg)

**Comment by ShaneKilkelly** [comment]
Yes, 2 :)

**Comment by reallinfo** [comment]
If you have another request, you can say. Please check it :)

https://github.com/ExHammer/hammer/pull/26

**Comment by ShaneKilkelly** [comment]
Merged, thanks!
