### ISSUE TITLE
Modifying ETS table to a :set?

### ISSUE THREAD

**Issue by tanguilp** [ExHammer/hammer#36]
Hi,

Here https://github.com/ExHammer/hammer/blob/master/lib/hammer/backend/ets.ex#L138 we can see that the ETS table is an `ordered_set`. It seems to me that ordered_set are slower than `set` in most cases, except when doing traversal on some close keys. I can't see, however, where this property of `ordered_set` could be used. Is there a rational for using it?

Regards

**Comment by ShaneKilkelly** [comment]
Yup, good catch.

I'll try changing it and see how it goes, thanks for the input :)
