### ISSUE TITLE
state of this project?

### ISSUE THREAD

**Issue by epinault** [ExHammer/hammer#48]
Is this still maintained? I see MR that are waiting to be merged for a long while. Do we need more maintainer?

**Comment by epinault** [comment]
@JuneKelly do you know?

**Comment by epinault** [comment]
@Gazler @sobolevn @slashdotdash @rosswilson  There are people who are willing to help and contribute if you are too busy and need new maintainers. But can any of you help us ? I have a fork with all we need but I would much prefer to keep this alive

**Comment by JuneKelly** [comment]
Yeah, I don't have a lot of spare time these days, and I don't work much with Elixir recently. I'd be happy to hand the project over to a group that wanted to continue development.

**Comment by rafaelsiqueira** [comment]
> Yeah, I don't have a lot of spare time these days, and I don't work much with Elixir recently. I'd be happy to hand the project over to a group that wanted to continue development, with the provision that I get a credit in the README ;)

Count me in!

**Comment by epinault** [comment]
Same. And happy to leave credits to your work and others . Maybe a credits.MD ?

**Comment by epinault** [comment]
@JuneKelly let us know what needs to be done ? can you add me ad owner/admin or something? then I can add @rafaelsiqueira

**Comment by epinault** [comment]
@JuneKelly I know you must be busy but if you could just help us to be added , then we can start taking over ?

**Comment by rafaelsiqueira** [comment]
Any news on this? @JuneKelly @epinault

**Comment by epinault** [comment]
@rafaelsiqueira still waiting on @JuneKelly to add me to the repo as owner 😢  or @sobolevn @reallinfo @slashdotdash @rosswilson

**Comment by rosswilson** [comment]
@epinault I’m not an admin of this repo, I think I was just involved in an issue or PR some time ago

**Comment by JuneKelly** [comment]
Sorry, I've been real busy. I've invited @epinault to the organization

**Comment by JuneKelly** [comment]
@epinault, I think I could also transfer ownership of the artifact on hex.pm?

**Comment by epinault** [comment]
That would be great as well! Same account name on hex pm

**Comment by epinault** [comment]
@JuneKelly we might need it also for the backend-redis?

**Comment by JuneKelly** [comment]
Indeed. I'll transfer as soon as I can.

And thanks for taking this on! ❤️

**Comment by epinault** [comment]
for sure ! thanks! I ll create an MR with a CREDITS.md this weekend

**Comment by epinault** [comment]
@rafaelsiqueira I ll make sometime this week to merge my fork into it

**Comment by JuneKelly** [comment]
OK, I've transfered ownership on hex.pm to epinault for the following packages:

- https://hex.pm/packages/hammer
- https://hex.pm/packages/hammer_plug
- https://hex.pm/packages/hammer_backend_redis
- https://hex.pm/packages/hammer_backend_mnesia

(note: the account listed as "publisher" on there is my previous name. I go by `June Kelly` now)
