### ISSUE TITLE
Bad Hexdocs URL in About section

### ISSUE THREAD

**Issue by andreh11** [ExHammer/hammer#58]
Should be https://hexdocs.pm/hammer/ instead of https://hexdocs.pm/ExHammer/hammer

**Comment by JuneKelly** [comment]
Thanks for opening this issue! 

Can you be more specific where you're seeing this? I can't find any references to `https://hexdocs.pm/ExHammer/hammer` in the (current) codebase.

**Comment by andreh11** [comment]
I'm sorry, I wasn't specific enough. It was talking about the Github repo's About section: 
![image](https://github.com/ExHammer/hammer/assets/46482611/9a69198d-8042-4375-a497-e7272fc9cc51)

**Comment by JuneKelly** [comment]
Ah, the sidebar, the one place I never look :sweat_smile: 

Thanks!
