### ISSUE TITLE
More Backends

### ISSUE THREAD

**Issue by JuneKelly** [ExHammer/hammer#7]
We should have more backends, because this project aims to be maximally useful in a variety of architectures. Perhaps:

- Mnesia
- Postgres (or a generic SQL backend? Probably Ecto)
- MongoDB
- ???

**Comment by sobolevn** [comment]
I can help with `ecto` backend. 
Could you please create a repo for me?

**Comment by ShaneKilkelly** [comment]
@sobolevn, done (https://github.com/ExHammer/hammer-backend-ecto) and thanks :)

**Comment by ShaneKilkelly** [comment]
Just a brain-wave, a Riak backend would also be cool.

**Comment by lpil** [comment]
One that uses distributed Erlang with no external dependency would be useful :)

**Comment by sobolevn** [comment]
There is `ets` backend. https://github.com/ExHammer/hammer/blob/master/lib/hammer/backend/ets.ex

**Comment by lpil** [comment]
But it's hard coded to be registered locally rather than globally, so it cannot be used in this way in a straightforward manner.

**Comment by ShaneKilkelly** [comment]
Good point, I’ll look into making it distribu-able this week

**Comment by lpil** [comment]
Thank you

**Comment by ShaneKilkelly** [comment]
I'm also wondering if maybe an Mnesia backend would be appropriate for the same use-case. Will investigate also.

**Comment by lpil** [comment]
Mnesia has some flaws, such as struggling with network partitions. What would we gain by using Mnesia over plain old ETS?

**Comment by ShaneKilkelly** [comment]
Update: I've had a hard time finding energy and time to work on this, but it's still very much on my radar. Will try to get distributable-ets done over the december holidays. Pull-requests always welcome of course, but I'm hoping to get some traction on this soon. :)

**Comment by lpil** [comment]
Cool, thank you :)

We're using Redis in production at the moment and it's working really well so please don't feel any urgency from us

**Comment by ShaneKilkelly** [comment]
@lpil , that's great to hear :) I'm glad it's working well in production.

**Comment by sudostack** [comment]
This is a neat library. Since you've already defined an interface for backends, I am recommending that before more backends are created, we take the effort to use facilities provided by Elixir to standardize the API by way of [**behaviours**](https://elixir-lang.org/getting-started/typespecs-and-behaviours.html#behaviours). WDYT?

If others agree, I could (when some time frees up) submit a PR to do this

**Comment by ShaneKilkelly** [comment]
Mnesia backend started here: https://github.com/ExHammer/hammer-backend-mnesia

**Comment by epinault** [comment]
@jared-mackey seems like an interesting idea. what backend are currently supported with Nebulex?

**Comment by florius0** [comment]
It would be nice to have atomics backend (like https://github.com/farhadi/rate_limiter does it) with crdt distribution.

**Comment by epinault** [comment]
@florius0  see https://github.com/ExHammer/hammer/pull/72 . Seems. @ruslandoga was looking at that but not sure if he made any progress on cutting his MR smaller
