### ISSUE TITLE
Create behavior 

### ISSUE THREAD

**Issue by sobolevn** [ExHammer/hammer#8]
Right now [this doc](https://github.com/ExHammer/hammer/blob/master/doc_src/CreatingBackends.md) describes a good use case for a [`behavior`](https://elixir-lang.org/getting-started/typespecs-and-behaviours.html#behaviours). Here's a good example: [`ueberauth`](https://github.com/ueberauth/ueberauth/blob/fbeba85955caa44754f2fb8ba3041da1ef9916a5/lib/ueberauth/strategy.ex).

So, my idea is to create a `behavior` for all other backends to implement.

What do you think?

**Comment by ShaneKilkelly** [comment]
Was thinking the same last week and forgot to document it. I can pick this up in the morning

**Comment by ShaneKilkelly** [comment]
Hoping to get time for this tomorrow :) shouldn't be too hard.

**Comment by ShaneKilkelly** [comment]
As a result of this, any external backend packages (such as Redis) will need to depend on Hammer explicitly. Not a big deal, just a minor breaking change to be aware of.

**Comment by ShaneKilkelly** [comment]
Pull Request: https://github.com/ExHammer/hammer/pull/10

**Comment by ShaneKilkelly** [comment]
Done
