### ISSUE TITLE
Specifying backends via config

### ISSUE THREAD

**Issue by sobolevn** [ExHammer/hammer#9]
Right now it is only possible to specify a backend via `keyword` argument.
I think, that it would be a nice feature to implement basic `mix` config for this task.

Something like:

```elixir
use Mix.Config

config :hammer, Hammer,
   backend: Hammer.Backend.ETS
```

**Comment by ShaneKilkelly** [comment]
I think this would be a good line of investigation, maybe for a version2, api-breaking release.

Can we do it without making `hammer` an OTP application?

**Comment by sobolevn** [comment]
> Can we do it without making hammer an OTP application?

I am quite sure that it is possible. Here's an example: https://github.com/samueljseay/recaptcha

**Comment by ShaneKilkelly** [comment]
Done in v2.0.0
